package use_cases.par_show_notification_use_case;

public interface ParShowNotificationInputBoundary {
    ParShowNotificationResponseModel showNotification(ParShowNotificationRequestModel requestModel) throws ClassNotFoundException;
}